#!/bin/bash

# Remote Database Docker Images - Deployment Options
# =================================================

echo "🐳 DOCKER DEPLOYMENT OPTIONS WITH REMOTE DATABASE"
echo "================================================="
echo ""
echo "1️⃣  LOCAL DEPLOYMENT (Current Configuration):"
echo "   docker compose up -d"
echo "   - Uses locally built images: etl-*:latest"
echo "   - Points to remote DB: 192.168.0.190"
echo "   - Status: ✅ Currently running"
echo ""
echo "2️⃣  DOCKER HUB DEPLOYMENT:"
echo "   # Update docker-compose.yml to use registry images:"
echo "   sed -i 's|image: etl-extract:latest|image: YOUR_USERNAME/etl-extract:remote-db-v1.0.0|g' docker-compose.yml"
echo "   sed -i 's|image: etl-transform:latest|image: YOUR_USERNAME/etl-transform:remote-db-v1.0.0|g' docker-compose.yml"
echo "   sed -i 's|image: etl-load:latest|image: YOUR_USERNAME/etl-load:remote-db-v1.0.0|g' docker-compose.yml"
echo "   docker compose up -d"
echo ""
echo "3️⃣  KUBERNETES DEPLOYMENT:"
echo "   # Update k8s/deployment.yaml with your registry:"
echo "   sed -i 's|your-registry.com|YOUR_USERNAME|g' k8s/deployment.yaml"
echo "   kubectl apply -f k8s/deployment.yaml"
echo ""
echo "4️⃣  HYBRID DEPLOYMENT (Local Kafka + Remote Everything):"
echo "   # Keep Kafka local, deploy services to K8s"
echo "   docker compose up -d kafka kafka-ui"
echo "   kubectl apply -f k8s/deployment.yaml"
echo ""
echo "📋 IMAGE CONFIGURATIONS AVAILABLE:"
echo ""
echo "   LOCAL IMAGES:"
echo "   - etl-extract:latest"
echo "   - etl-transform:latest"  
echo "   - etl-load:latest"
echo ""
echo "   REGISTRY READY:"
echo "   - your-dockerhub-username/etl-extract:remote-db-v1.0.0"
echo "   - your-dockerhub-username/etl-transform:remote-db-v1.0.0"
echo "   - your-dockerhub-username/etl-load:remote-db-v1.0.0"
echo ""
echo "🔧 CONFIGURATION FILES READY:"
echo "   ✅ .env - Remote database configuration"
echo "   ✅ docker-compose.yml - Local deployment with remote DB"
echo "   ✅ k8s/deployment.yaml - Kubernetes deployment"
echo "   ✅ build_and_push.sh - Image building and registry push"
echo ""
echo "🎯 ALL SCENARIOS COVERED:"
echo "   ✅ Development: Local images + Remote database"
echo "   ✅ Staging: Registry images + Remote database"
echo "   ✅ Production: Kubernetes + Remote database"
echo "   ✅ Hybrid: Mix of local and remote components"
echo ""
echo "🚀 READY FOR ANY DEPLOYMENT TARGET!"
